name: min_ds-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - anyio=4.11.0=pyhcf101f3_0
  - argon2-cffi=25.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=25.1.0=py311h49ec1c0_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attr=2.5.2=h39aace5_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py311h1ddb823_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h3394656_0
  - cattrs=25.2.0=pyhd8ed1ab_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=2.0.0=py311h5b438cf_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311hdf67eae_2
  - curl=8.14.1=h332b0f4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py311h3778330_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - git=2.42.0=pl5321h7bc287a_1
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glib=2.84.2=h6a678d5_0
  - glib-tools=2.84.2=h6a678d5_0
  - graphite2=1.3.14=hecca717_2
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.3.3=hbb57e21_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_genutils=0.2.0=pyhd8ed1ab_2
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - json5=0.12.1=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py311h38be061_2
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jsonschema-with-format-nongpl=4.25.1=he01879c_0
  - jupyter-lsp=2.3.0=pyhcf101f3_0
  - jupyter-server-mathjax=0.2.6=pyhbbac1ac_2
  - jupyter_client=7.4.9=pyhd8ed1ab_0
  - jupyter_contrib_core=0.4.0=pyhd8ed1ab_1
  - jupyter_contrib_nbextensions=0.7.0=pyhd8ed1ab_0
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_highlight_selected_word=0.2.0=pyhd8ed1ab_1006
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.6.1=pyhd8ed1ab_0
  - jupyter_server=2.17.0=pyhcf101f3_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.0.7=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_0
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lark=1.3.0=pyhd8ed1ab_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - lerc=4.0.0=h0aef613_1
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=20_linux64_openblas
  - libclang-cpp20.1=20.1.8=default_h99862b1_4
  - libclang13=21.1.0=default_h746c552_1
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_5
  - libgpg-error=1.55=h3f2d84a_0
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=20_linux64_openblas
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.1=h8261f1e_0
  - libuuid=2.41.2=he9a06e4_0
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lxml=4.9.3=py311h1a07684_3
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib=3.8.0=py311h38be061_2
  - matplotlib-base=3.8.0=py311h54ef318_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.4=pyhcf101f3_0
  - mpg123=1.32.9=hc50e24c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - nbclassic=1.3.3=pyhcf101f3_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert=7.16.6=hb482800_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbconvert-pandoc=7.16.6=hed9df3c_0
  - nbdime=3.2.1=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - notebook=6.5.7=pyha770c72_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.37=h29cc59b_0
  - nss=3.116=h445c969_0
  - numpy=1.26.0=py311h64a7726_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openpyxl=3.1.2=py311h459d7ec_1
  - openssl=3.5.4=h26f9b46_0
  - outcome=1.3.0.post0=pyhd8ed1ab_1
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.1.1=py311h320fe9a_1
  - pandoc=3.8.1=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.42=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h98278a2_3
  - pip=23.3.2=pyhd8ed1ab_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - plotly=5.17.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - prometheus_client=0.23.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py311h49ec1c0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=hac146a9_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pyqt=5.15.11=py311he22028a_1
  - pyqt5-sip=12.17.0=py311hfdbb021_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.5=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311h2315fbb_0
  - qt-main=5.15.15=hea1682b_4
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-cache=1.1.1=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rfc3987-syntax=1.1.0=pyhe01879c_1
  - rpds-py=0.27.1=py311h902ca64_1
  - scikit-learn=1.3.1=py311hc009520_1
  - scipy=1.11.3=py311h64a7726_1
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - selenium=4.15.2=pyhd8ed1ab_0
  - selenium-manager=4.15.0=he8a937b_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.9.0=pyhff2d567_0
  - sip=6.10.0=py311h1ddb823_1
  - six=1.17.0=pyhe01879c_1
  - smmap=5.0.2=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311h0372a8f_1
  - tenacity=9.1.2=pyhd8ed1ab_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - tornado=6.5.2=py311h49ec1c0_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trio=0.31.0=py311h3d13dd8_0
  - trio-websocket=0.12.2=pyh29332c3_0
  - types-python-dateutil=2.9.0.20250822=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - ujson=5.11.0=py311hc665b79_1
  - unicodedata2=16.0.0=py311h49ec1c0_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - url-normalize=2.2.1=pyhd8ed1ab_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - wsproto=1.2.0=pyhd8ed1ab_1
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py311haee01d2_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - black==25.9.0
      - click==8.3.0
      - jupyter-black==0.4.0
      - mypy-extensions==1.1.0
      - pathspec==0.12.1
      - pytokens==0.1.10
      - tokenize-rt==6.2.0
prefix: /home/kehuydiet/miniconda3/envs/min_ds-env
